name: ci

on:
  push:
    branches:
      - custom
  workflow_dispatch:

env:
  JENKINS_VERSION: 2.332.3
  JENKINS_SHA: d193f179aadf3a7ceb61adebc3ab51218ac4a7852b88932ff33b44fd7be6010f

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: build
        run: |
          make build-rhel_ocp_ubi8_jdk11

      -
        name: inspect
        run: |
          docker images

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          VERSION=${JENKINS_VERSION}-rhel-ocp-ubi8-jdk11

          docker tag jenkins/jenkins:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
